### ISSUE TITLE
是不是更新的太慢了

### ISSUE THREAD

**Issue by fekata** [jingsam/iview-theme#5]
貌似生成的css和iview的样式有差别

**Comment by jingsam** [comment]
建议通过变量覆盖的方式生成主题，文档如下：
https://www.iviewui.com/docs/guide/theme#%E5%8F%98%E9%87%8F%E8%A6%86%E7%9B%96%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89

iview-theme总是会拉取最新版本的iview.css, 很容易和你用的版本不匹配

**Comment by fekata** [comment]
@jingsam 感谢，已解决
（我们系统是根据不同用户权限自动匹配颜色，所以现在的解决方案就是随着iview更新，我就重新通过工具生成一遍css）
