### ISSUE TITLE
iview-theme build -o dist/编译后tabs组件缺少 样式导致渲染错误

### ISSUE THREAD

**Issue by aaaaa1414514** [jingsam/iview-theme#6]
tabs组件 缺少 
.ivu-tabs-nav-scroll-disabled {
    display: none;
}
.ivu-tabs-nav-prev {
    position: absolute;
    line-height: 32px;
    cursor: pointer;
    left: 0;
}
.ivu-tabs-nav-next {
    position: absolute;
    line-height: 32px;
    cursor: pointer;
    right: 0;
}
.ivu-tabs-nav-scrollable {
    padding: 0 12px;
}
这几个 样式导致渲染错误

**Comment by jingsam** [comment]
将iview更新到最新版本
